### ISSUE TITLE
"Error: Forbidden" when Cotoami Scraper to Docker

### ISSUE THREAD

**Issue by moviefuns** [cotoami/cotoami#155]
Hello. Thanks for your cotoami project!
I've deployed cotoami docker using the script https://raw.githubusercontent.com/cotoami/cotoami/master/launch/run.sh .
Everything works but cotoami scraper. When it sends links or selections, the chrome addon pop up error msg "Error: Forbidden". 
Is there anything I can do to fix that?

**Comment by marubinotto** [comment]
@moviefuns I've just released a new version to fix this issue. Could you try it again to see if it works now?

**Comment by moviefuns** [comment]
Thanks.
Seems the problem caused by the domain name, as default by 'localhost'. I changed it to my domain name in docker-compose.yml. Works by now.
Thank you for the great work!

**Comment by kroschu** [comment]
Have the same problem. My docker-compose.yml :

```
version: '2'
services:

  cotoami:
    image: cotoami/cotoami:latest
    ports:
      - "443:4000"
    links:
      - redis
      - postgres
      - neo4j
    environment:
      SECRET_KEY_BASE: iirr+1hGL0ew7N/jQmnQ2crnwBBwjHWPkM/QZk7tmD8/ARQhvAH4j69wh1WHH7gv
      COTOAMI_URL_SCHEME: https
      COTOAMI_URL_HOST: km.uabp.ml
      COTOAMI_REDIS_HOST: redis
      COTOAMI_REPO_USER: postgres
      COTOAMI_REPO_PASSWORD: postgres
      COTOAMI_REPO_DATABASE: cotoami
      COTOAMI_REPO_HOST: postgres
      COTOAMI_NEO4J_HOST: neo4j
      COTOAMI_EMAIL_FROM: no-reply@cotoa.me
      COTOAMI_ADDITIONAL_VALID_ORIGINS: chrome-extension://
      COTOAMI_SMTP_SERVER: smtp.gmail.com 
      COTOAMI_SMTP_PORT: "587"
      COTOAMI_URL_PORT: "443"
      COTOAMI_SMTP_USER: tukroschu@gmail.com
      COTOAMI_SMTP_PASSWORD: ****************
      COTOAMI_EMAIL_FROM: tukroschu@gmail.com
      COTOAMI_OWNER_EMAILS: tukroschu@gmail.com
      
  redis:
    image: redis:alpine

  postgres:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cotoami
    volumes:
      - postgres-data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:3.2.2
    environment:
      NEO4J_AUTH: none
    volumes:
      - neo4j-data:/data 
 

volumes:
  postgres-data:
  neo4j-data:
```
Please tell me what I need to fix.

**Comment by marubinotto** [comment]
@kroschu `COTOAMI_ADDITIONAL_VALID_ORIGINS` appears to be no problem. How about your `Cotoami URL` in Cotoami Scraper Options? It should be https://km.uabp.ml

**Comment by kroschu** [comment]
![A7133889-A993-4B4E-B98F-A22EA5FB0ABC](https://user-images.githubusercontent.com/10142684/67781598-58867a00-fa70-11e9-868a-375c932c75ff.jpeg)
![5B1D5C02-FE19-4715-A78B-9AE6A8EFC127](https://user-images.githubusercontent.com/10142684/67781600-591f1080-fa70-11e9-9d25-d925f4de5de8.jpeg)

The settings are correct, and I am authorized on the server, but the scraper still does not work.
Maybe I should configure my browser?   It not work on your side too?

**Comment by marubinotto** [comment]
@kroschu Could you post the logs of the cotoami container when "Error: Forbidden" is shown?

**Comment by kroschu** [comment]
2019-10-30T14:52:10.806396139Z 14:52:10.804 [info] Connecting: SFMyNTY.g3QAAAACZAAEZGF0YW0AAAAkYzI0OGY5MDAtYjNhMS00MmMyLWJlNWQtMjc4ZmUyMWE4OWM2ZAAGc2lnbmVkbgYAezMmHW4B.xV9QGgUhJHn3jow84EQ7kbpxd0iCk4fDl1jTGAbDFoI


2019-10-30T14:52:13.310895200Z 14:52:13.309 request_id=2n978lh8tpk0664bjs0001h2 [info] Header 'x-cotoami-client-id' does not exist


2019-10-30T14:52:13.315212274Z 14:52:13.314 request_id=2n978lh8tpk0664bjs0001h2 [info] assign_amishi: %{__meta__: #Ecto.Schema.Metadata<:loaded, "amishis">, __struct__: Cotoami.Amishi, auth_id: nil, auth_provider: nil, avatar_url: "https://secure.gravatar.com/avatar/f629b8ac9b84cfdcfeba454024e6ba58", disabled: false, email: "tukroschu@gmail.com", id: "c248f900-b3a1-42c2-be5d-278fe21a89c6", inserted_at: #DateTime<2019-10-28 06:27:41.036771Z>, invite_limit: 0, inviter: #Ecto.Association.NotLoaded<association :inviter is not loaded>, inviter_id: nil, name: "tukroschu", owner: true, updated_at: #DateTime<2019-10-28 06:27:41.087256Z>}


2019-10-30T14:52:13.317141295Z 14:52:13.315 request_id=2n978lh8tpk0664bjs0001h2 [info] state=set duration=7.310 status=200 params={} path=/api/public/session method=GET format=json controller=CotoamiWeb.SessionController action=index user_token=tukroschu@gmail.com request_id=2n978lh8tpk0664bjs0001h2


2019-10-30T14:52:21.039213095Z 14:52:21.038 request_id=2n978lvlingv02qkag0001hi [info] Header 'x-cotoami-client-id' does not exist


2019-10-30T14:52:21.043361368Z 14:52:21.042 request_id=2n978lvlingv02qkag0001hi [info] assign_amishi: %{__meta__: #Ecto.Schema.Metadata<:loaded, "amishis">, __struct__: Cotoami.Amishi, auth_id: nil, auth_provider: nil, avatar_url: "https://secure.gravatar.com/avatar/f629b8ac9b84cfdcfeba454024e6ba58", disabled: false, email: "tukroschu@gmail.com", id: "c248f900-b3a1-42c2-be5d-278fe21a89c6", inserted_at: #DateTime<2019-10-28 06:27:41.036771Z>, invite_limit: 0, inviter: #Ecto.Association.NotLoaded<association :inviter is not loaded>, inviter_id: nil, name: "tukroschu", owner: true, updated_at: #DateTime<2019-10-28 06:27:41.087256Z>}


2019-10-30T14:52:21.049879163Z 14:52:21.048 request_id=2n978lvlingv02qkag0001hi [info] state=set duration=11.698 status=200 params={"query":"t"} path=/api/cotonomas/suggestions/t method=GET format=json controller=CotoamiWeb.CotonomaController action=suggest user_token=tukroschu@gmail.com request_id=2n978lvlingv02qkag0001hi


2019-10-30T14:52:23.850817575Z 14:52:23.849 [info] Connecting: SFMyNTY.g3QAAAACZAAEZGF0YW0AAAAkYzI0OGY5MDAtYjNhMS00MmMyLWJlNWQtMjc4ZmUyMWE4OWM2ZAAGc2lnbmVkbgYAezMmHW4B.xV9QGgUhJHn3jow84EQ7kbpxd0iCk4fDl1jTGAbDFoI


2019-10-30T14:52:24.899734618Z 14:52:24.897 request_id=2n978m6rj15a8cd36g0001i2 [info] origin header: null


2019-10-30T14:52:24.900573802Z 14:52:24.897 request_id=2n978m6rj15a8cd36g0001i2 [info] state=set duration=1.585 status=403 params={"name":"test"} path=/api/cotonomas/name/test method=PUT request_id=2n978m6rj15a8cd36g0001i2


2019-10-30T14:52:37.815525981Z 14:52:37.813 [info] Connecting: SFMyNTY.g3QAAAACZAAEZGF0YW0AAAAkYzI0OGY5MDAtYjNhMS00MmMyLWJlNWQtMjc4ZmUyMWE4OWM2ZAAGc2lnbmVkbgYAezMmHW4B.xV9QGgUhJHn3jow84EQ7kbpxd0iCk4fDl1jTGAbDFoI

**Comment by marubinotto** [comment]
@kroschu 

> origin header: null

Your browser appears not to send a valid `Origin` header (it should not be`null` by default). Did you customize your browser's settings?

**Comment by kroschu** [comment]
On another computer later install a clean system, Windows 7 + Chrome browser. I will try without authorization in the browser. I will write about the result. Thanks.

**Comment by kroschu** [comment]
Everything works correctly. Thanks a lot!
